sudo: required
dist: trusty
language: node_js
node_js:
  - '9'
before_install:
  - export NODE_OPTIONS="--max_old_space_size=4096"
  - export PATH=$PATH:$(pwd)/node_modules/.bin
install:
  - npm i
before_script:
  - npm run network > /dev/null &
  - sleep 5
script:
  - npm run test
after_script:
  - npm run network-coverage > /dev/null &
  - travis_wait 40 npm run coverage && cat coverage/lcov.info | coveralls
